name: CI
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - main
jobs:
  CI:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1
      - uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "corretto"
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: npm
          cache-dependency-path: 'cdk/package-lock.json'
      - run: |
          (
            cd cdk
            npm ci
            npm run lint
            npm test
            npm run synth
          )
          
          sbt -v test scalafmtCheckAll
          sbt -v assembly

# TODO Update guardian/actions-riff-raff to make `sources` independent of the riff-raff.yaml file
#      - uses: guardian/actions-riff-raff@v1
#        with:
#          app: backend-101-scala-starter-akash1810
#          configPath: cdk/cdk.out/riff-raff.yaml

      # @guardian/node-riffraff-artifact requires riff-raff.yaml to sit next to artifact.json
      - name: Riff-Raff Upload
        run: |
          cp cdk/cdk.out/riff-raff.yaml riff-raff.yaml
          npx @guardian/node-riffraff-artifact
